name = "cool-snowflake-9f45"
main = "src/index.js"
compatibility_date = "2026-01-03"

[durable_objects]
bindings = [
  { name = "QUEUE", class_name = "Queue" },
  { name = "INDEX", class_name = "IndexDB" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Queue", "IndexDB"]

[triggers]
crons = ["* * * * *"] # every minute
