# wrangler.toml
name = 'cool-snowflake-9f45'
main = "src/index.js"
compatibility_date = "2025-01-03"

[[durable_objects.bindings]]
name = "QUEUE"
class_name = "Queue"

[[durable_objects.bindings]]
name = "INDEX"
class_name = "IndexDB"

[triggers]
crons = ["*/1 * * * *"]
